options:
  title:
    type: string
    description: Title to display in the navigation bar.
    default: Service Catalogue

  tagline:
    type: string
    description: |
      A one-liner that communicates the core value or purpose of the 
      bundle it is part of.
    default: Easy access to Charmed UIs

  description:
    type: string
    description: |
      A somewhat longer description of the bundle or set of charms the
      catalogue is displaying.
  
  links:
    type: string
    description: |
      JSON string containing the links to display in the catalogue. 
      Contains links to Charmhub, Mattermost and Discourse by default.
    default: |
      [
        {
          "category": "Documentation",
          "items": [
            {
              "name": "Charmhub",
              "url": "https://charmhub.io"
            }
          ]
        },
        {
          "category": "Social",
          "items": [
            {
              "name": "Ubuntu Matrix Community",
              "url": "https://matrix.to/#/#community:ubuntu.com",
              "target": "_blank"
            },
            {
              "name": "Discourse",
              "url": "https://discourse.charmhub.io",
              "target": "_blank"
            }
          ]
        }
      ]
