name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/pull-request.yaml@feat/self-hosted
    secrets: inherit
    with:
      charm-path: "charm"
