name: Release Charm

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - track/**

permissions:
  # Required for all workflows
  security-events: write
  # Only required for workflows in private repositories
  actions: read
  # Write permission needed for the reusable workflow to push git tags
  contents: write
  # Required for pushing rock to GHCR
  packages: write

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@v2
    secrets: inherit
    with:
      charm-path: charm
      default-track: dev

  release-rock:
    # rock-release-dev is actually releasing to ghcr in this case, as the `just release-ghcr` recipe is overridden
    uses: canonical/observability/.github/workflows/rock-release-dev.yaml@v2
    secrets: inherit
    with:
      rock-path: workload
