name: Release to Edge

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@main
    secrets: inherit
    with:
      charm-path: "charm"
